services:
  postgres:
    image: postgres:14
    container_name: andarna_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: andarna_local_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: olya@andarna.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  redis:
    image: redis:latest
    container_name: redis_store
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540" # Port for RedisInsight UI
    depends_on:
      - redis


volumes:
  postgres-data:
  pgadmin-data:
  redis-data: